### ISSUE TITLE
performance of plugin

### ISSUE THREAD

**Issue by matu3ba** [NTBBloodbath/cheovim#4]
Would be nice to have some elaboration on how much startup-time overhead this plugin creates for having many plugins in multiple profiles to see how this plugin scales.

I guess the runtime overhead is negligible, but is there a strategy how to show this (ie with screencast videos)?

**Comment by NTBBloodbath** [comment]
Hey, I'm pretty sorry for the really late reply, haven't had too much time recently.

The startup time delay shouldn't be really noticeable because cheovim loads the configurations (aka profiles) like they were actual plugins and we try to use libuv whenever is possible to speed up things instead of using the slow Vimscript functions and we don't do any real hard task besides creating missing directories and downloading setups / plugins managers but the download process is actually inside Neovim so it shouldn't increase the startup time.

**Comment by NTBBloodbath** [comment]
This should be more noticeable now thanks to v0.3 release and latest Neovim nightly (0.8, going to be released soon iirc) including profiling for Lua `require` calls.
